-- insert into user(id, name, login, password, created_at, updated_at, version) values (1,'Administrator','admin','$2a$10$WrAprIfLw2fVi/Nh/yxeBu3QiKU8KRgnwetFSs9WsfbyXPChv5WfK', timestamp(0), timestamp(0), 0);
-- insert into user(id, name, login, password, created_at, updated_at, version) values (2,'Test','test','$2a$10$WrAprIfLw2fVi/Nh/yxeBu3QiKU8KRgnwetFSs9WsfbyXPChv5WfK', timestamp(0), timestamp(0), 0);
-- insert into user(id, name, login, password, created_at, updated_at, version) values (3,'Guest','guest','$2a$10$WrAprIfLw2fVi/Nh/yxeBu3QiKU8KRgnwetFSs9WsfbyXPChv5WfK', timestamp(0), timestamp(0), 0);
--
-- insert into role(id, name, created_at, updated_at, version) values (1,'ROLE_USER', timestamp(0), timestamp(0), 0);
-- insert into role(id, name, created_at, updated_at, version) values (2,'ROLE_ADMIN', timestamp(0), timestamp(0), 0);
-- insert into role(id, name, created_at, updated_at, version) values (3,'ROLE_GUEST', timestamp(0), timestamp(0), 0);
--
-- insert into user_role(user_id, role_id) values (1,1);
-- insert into user_role(user_id, role_id) values (1,2);
-- insert into user_role(user_id, role_id) values (2,1);
-- insert into user_role(user_id, role_id) values (3,3);